data:
  image: "busybox"
  volumes:
    - /var/lib/mysql
db:
  image: "mysql:latest"
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data
web:
  build: ./
  environment:
    RAILS_ENV: production
  volumes:
    - /usr/src/app
  ports:
    - 3000
  links:
    - db
