#
# Data-only container
#
data:
  image: "busybox"
  volumes:
    - /var/lib/mysql
#
# MySQL
#
db:
  image: 'mysql:latest'
  environment:
    MYSQL_ROOT_PASSWORD: root
  volumes_from:
    - data

#
# Rails app
#
web:
  build: ./
  command: 'bundle exec unicorn -p 3000'
  environment:
    RAILS_ENV: development
  volumes:
    - .:/usr/src/app
  ports:
    - '3000:3000'
  links:
    - db
