#
# MySQL
#
db:
  image: 'mysql:latest'
  environment:
    MYSQL_ROOT_PASSWORD: root
#
# Load-balancer
#
lb:
  ports:
  - 80:3000
  restart: always
  tty: true
  image: rancher/load-balancer-service
  links:
    - web
  stdin_open: true
#
# Rails app
#
web:
  image: 'hub.howtocookmicroservices.com:5000/quotes:latest'
  command: 'bundle exec unicorn -p 3000'
  environment:
    RAILS_ENV: production
  ports:
    - '3000'
  links:
    - db
