default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  reconnect: true
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_3306_TCP_PORT'] || 'localhost' %>

development:
  <<: *default
  database: quotes_development

test:
  <<: *default
  database: quotes_test

production:
  <<: *default
  database: quotes_integration
