default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  reconnect: true

development:
  <<: *default
  database: quotes_development

test:
  <<: *default
  database: quotes_test

production:
  <<: *default
  database: quotes_integration
